name: Ping API daily

on:
  schedule:
    - cron: '0 0 * * *' # chạy mỗi ngày lúc 00:00 UTC
  workflow_dispatch:     # cho phép chạy thủ công từ tab Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call your API
        run: |
          curl -s -X GET https://ielts-scrape.onrender.com/scrape

